name: flutter_play_integrity_wrapper
description: A Flutter wrapper for the Google Play Integrity API on Android.
version: 0.0.2
repository: https://github.com/ArdaKoksall/flutter_play_integrity_wrapper
homepage: https://github.com/ArdaKoksall/flutter_play_integrity_wrapper

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_play_integrity_wrapper
        pluginClass: FlutterPlayIntegrityWrapperPlugin

